export const ROUTE_WELCOME_SCREEN = 'ROUTE_WELCOME_SCREEN ';
export const ROUTE_REGISTRATION_SCREEN = 'ROUTE_REGISTRATION_SCREEN ';
export const ROUTE_LOGIN_SCREEN = 'ROUTE_LOGIN_SCREEN ';
export const ROUTE_DASHBOARD = 'ROUTE_DASHBOARD ';
export const POSTLOGIN = 'POSTLOGIN ';